### ISSUE TITLE
Deprecation Issue

### ISSUE THREAD

**Issue by payne-chris-r** [ga-wdi-boston/ember-resources#34]
Jeff mentioned the browser is giving him an deprecation error. I'm trying to catch up to see it myself...

**Comment by payne-chris-r** [comment]
DEPRECATION: Overriding Date.parse with Ember.Date.parse is deprecated. Please set ENV.EmberENV.EXTEND_PROTOTYPES.Date to false in config/environment.js

// config/environment.js
ENV = {
  EmberENV: {
    EXTEND_PROTOTYPES: {
      Date: false,
    }
  }
}
 [deprecation id: ds.date.parse-deprecate]
        at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:16479:7)
        at raiseOnDeprecation (http://localhost:4200/assets/vendor.js:16387:12)
        at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:16479:7)
        at invoke (http://localhost:4200/assets/vendor.js:16495:7)
        at deprecate (http://localhost:4200/assets/vendor.js:16448:32)
        at Object.deprecate (http://localhost:4200/assets/vendor.js:26487:37)
        at deprecate (http://localhost:4200/assets/vendor.js:70601:40)
        at Module.callback (http://localhost:4200/assets/vendor.js:70722:42)
        at Module.exports (http://localhost:4200/assets/vendor.js:131:32)

**Comment by jrhorn424** [comment]
Yo, fence code blocks much?

**Comment by jrhorn424** [comment]
Now tracked at template.
