### ISSUE TITLE
Error after deleting a Pokemon

### ISSUE THREAD

**Issue by GA-MEB** [ga-wdi-boston/ember-resources#7]
Maybe trying to reload the Pokemon after it's been destroyed?

```
Error: Attempted to handle event `notFound` on <ember-repo-template@model:pokemon::ember474:1> while in state root.deleted.saved. 
    at new Error (native)
    at Error.EmberError (http://localhost:4200/assets/vendor.js:25269:21)
    at ember$data$lib$system$model$internal$model$$InternalModel._unhandledEvent (http://localhost:4200/assets/vendor.js:126790:15)
    at ember$data$lib$system$model$internal$model$$InternalModel.send (http://localhost:4200/assets/vendor.js:126668:16)
    at ember$data$lib$system$model$internal$model$$InternalModel.notFound (http://localhost:4200/assets/vendor.js:126578:14)
    at http://localhost:4200/assets/vendor.js:123331:23
    at tryCatch (http://localhost:4200/assets/vendor.js:61667:14)
    at invokeCallback (http://localhost:4200/assets/vendor.js:61682:15)
    at publish (http://localhost:4200/assets/vendor.js:61650:9)
    at publishRejection (http://localhost:4200/assets/vendor.js:61585:5)onerrorDefault @ ember.debug.js:30877exports.default.trigger @ ember.debug.js:52928(anonymous function) @ ember.debug.js:54177Queue.invoke @ ember.debug.js:320Queue.flush @ ember.debug.js:384DeferredActionQueues.flush @ ember.debug.js:185Backburner.end @ ember.debug.js:563Backburner.run @ ember.debug.js:685run @ ember.debug.js:20105hash.error @ rest-adapter.js:761fire @ jquery.js:3099self.fireWith @ jquery.js:3211done @ jquery.js:8266(anonymous function) @ jquery.js:8605(anonymous function) @ fake_xml_http_request.js:137dispatchEvent @ fake_xml_http_request.js:181_readyStateChange @ fake_xml_http_request.js:371_setResponseBody @ fake_xml_http_request.js:431respond @ fake_xml_http_request.js:452(anonymous function) @ pretender.js:303resolve @ pretender.js:340(anonymous function) @ pretender.js:331
```

**Comment by GA-MEB** [comment]
Invested another hour on this one today. Still not sure what the problem is. Possibly something related to Mirage?

**Comment by GA-MEB** [comment]
No longer an issue with current code.
